
services:
  agent:
    build: .
    depends_on:
      - redis # Redis for caching
    ports:
      - "8000:8000"          # Prometheus scrape
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0  
    # Example command – overridden by `docker compose run`
    command: ["Who won the 2022 FIFA World Cup?"]

   # ───── OpenTelemetry collector ─────
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.98.0
    command: ["--config=/etc/otel.yaml"]
    volumes:
      - ./otel.yaml:/etc/otel.yaml:ro
    ports:
      - "4318:4318"        # OTLP/HTTP  (traces from the agent)
      - "8888:8888"        # Collector's own Prometheus metrics

  # ───── Redis service ─────
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"          # For local redis-cli
    command: ["redis-server", "--save", "''",  "--appendonly", "no"]