version: "3.9"

services:
  agent:
    build: .
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
      BING_API_KEY:   ${BING_API_KEY:-}
    # Example command – overridden by `docker compose run`
    command: ["Who won the 2022 FIFA World Cup?"]
