
services:
  agent:
    build: .
    ports:
      - "8000:8000"          # Prometheus scrape
    env_file:
      - .env
    # Example command – overridden by `docker compose run`
    command: ["Who won the 2022 FIFA World Cup?"]

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.98.0
    command: ["--config=/etc/otel.yaml"]
    volumes:
      - ./otel.yaml:/etc/otel.yaml:ro
    ports:
      - "4318:4318"        # OTLP/HTTP  (traces from the agent)
      - "8888:8888"        # Collector's own Prometheus metrics